version: '3.8'

services:
  load-generator:
    build: .
    environment:
      - TARGET_URL=https://pinetswap.net/piswap.html
      - NUM_WORKERS=400
      - REQUEST_DELAY=10ms
      - STATS_INTERVAL=5s
      - MAX_RPS=1000
    deploy:
      replicas: 5  # Number of replicas to run
    restart: unless-stopped
    # Resource limits to prevent system overload
    mem_limit: 256m
    cpus: 0.5
    
  # Alternative: Define multiple named services if you need different configs
  load-generator-1:
    build: .
    environment:
      - TARGET_URL=https://pinetswap.net/piswap.html
      - NUM_WORKERS=300
      - REQUEST_DELAY=20ms
      - MAX_RPS=500
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25
    profiles: ["manual"] # Only runs when explicitly specified
    
  load-generator-2:
    build: .
    environment:
      - TARGET_URL=https://pinetswap.net/piswap.html
      - NUM_WORKERS=300
      - REQUEST_DELAY=50ms
      - MAX_RPS=200
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25
    profiles: ["manual"]

# Optional: Create a network for the containers
networks:
  default:
    name: load-test-network